# Generated by Django 2.2.4 on 2020-02-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200216_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
