# Generated by Django 2.2.4 on 2020-02-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlItem', '0002_auto_20200203_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
